PORTNAME=	zmq
PORTVERSION=	1.1.3.s20250122
CATEGORIES=	net pear

MAINTAINER=	daniel@morante.net
COMMENT=	ZeroMQ bindings for PHP
WWW=		https://github.com/zeromq/php-zmq

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

LIB_DEPENDS=	libzmq.so:net/libzmq4

USES=		php:pecl pkgconfig
USE_GITHUB=	yes
GH_ACCOUNT=	zeromq
GH_PROJECT=	php-zmq
GH_TAGNAME=	616b6c64ffd3866ed038615494306dd464ab53fc

.include <bsd.port.mk>
