# FreeBSD zetacoind configuration file

# This file is used by zetacoind
# The GUI and CLI will default to generating and using ~/.zetacoin/zetacoin.conf
#
# A generator for some common configurations exists at
# https://jlopp.github.io/bitcoin-core-config-generator/

# Bind to given address and always listen on it. Use [host]:port notation for IPv6
#bind=<addr>

# Specify your own public IP address.
#externalip=<ip>

# Listen for incoming connections on non-default port.
#port=17333

# Connect via a SOCKS5 proxy
#proxy=127.0.0.1:9050
